Awesome books classes
AJ193/Awesome-books pull request #3
Opened 2023-04-25 12:08 UTC by Theodoraldo

At this stage, we
- Added classes to book functionality.
- Update CSS file.
- Update index.html file.

2023-04-25 17:16 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @Theodoraldo and @AJ193,

### Nice job, you are almost there.

![cat-driving-serious](https://user-images.githubusercontent.com/68796232/223284600-852bcd90-1495-4a40-8515-cc12636b369b.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below ⬇️.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-04-25 17:16 UTC, Omar-Muhamad commented on main.js
>  // Removing  data from localStorage
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-javascript/blob/main/books/m2_plain_js_classes_v1_1.md#:~:text=it%20inside%20classes.-,Create%20class%20methods%20to%20add%20and%20remove%20books.,-Maintain%20all%20of), Kindly add this `removeItem` function as a method to the `NewBook` class you created above

2023-04-25 17:16 UTC, Omar-Muhamad commented on main.js
> +      `;
- [ ] [Optional] You can also add this function as a method inside `NewBook` class you created.

2023-04-26 00:10 UTC, Reem-lab approved these changes
# Hi @Theodoraldo and @AJ193,👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🔥🔥💯💯
<img src="https://media2.giphy.com/media/3o6fJ1BM7R2EBRDnxK/giphy.gif"/>

## Highlights 🔥🔥🔥🔥
- Followed GitHub flow ✅
- Great working on the functionality 🔥🔥
- Great working on the requested changes 🚀





## Optional suggestions



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 00:15 UTC, merged